name = "remix-mdn2e"
type = "javascript"
compatibility_date = "2022-03-02"

zone_id = ""
account_id = "ffc27d2c4ab35f6e6f2dc63e87cd82d3"
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"


[miniflare]
kv_persist = true